apiVersion: v1
kind: Service
metadata:
    name: docker-assignment
spec:
    selector:
        app: docker-assignment
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
          nodePort: 30010
    type: LoadBalancer
